### ISSUE TITLE
这个怎么用?

### ISSUE THREAD

**Issue by Erane** [kawaiiz/table_component#1]
复制你源码?可是你源码里面路径很多是写死的

**Comment by mmmml-zhao** [comment]
> 复制你源码?可是你源码里面路径很多是写死的

更新了readme.md，重新pull一下，我已经试了，按流程可以跑通。

**Comment by kawaiiz** [comment]
> 复制你源码?可是你源码里面路径很多是写死的

更新了readme.md，我已经试了，可以跑通。
