### ISSUE TITLE
datalist数据变化后，wxml渲染异常

### ISSUE THREAD

**Issue by mengqian277** [kawaiiz/table_component#11]
场景出现在分页数据，当向下翻页时，数据量相同（比如每页10条）时，不会出现问题，但是当后面一页（A页）的数据量少于上一页（B页）时，往回翻页后（回到B页），那么B页渲染的数据就只有A页datalist.length条，实际上B页的datalist数据量还是10条，但是不能渲染出来。
![image](https://user-images.githubusercontent.com/98152710/218959276-f00ab869-bc15-4615-ad72-7d5ab13d57e1.png)
![image](https://user-images.githubusercontent.com/98152710/218959346-5d556d2c-ae87-479f-88c0-bcea2ae41890.png)
![image](https://user-images.githubusercontent.com/98152710/218959504-2def6aef-ab80-42dc-a5d6-ac4e83ca15e7.png)

**Comment by mmmml-zhao** [comment]
这样我也不清楚这是什么原因
给你几个排查点
1.  page里 dataList 是通过 this.setData更新的嘛
2. 可以在下面的图片的地方 console一下
![image](https://user-images.githubusercontent.com/25151442/218976536-20db2d2f-eaeb-40ea-9ed0-561837ea0bde.png)
3. 看看 rowKey 字段 是不是保持唯一的。

既然是数据不对，你就通过console跟踪一下 数据在各个组件中的状态。

**Comment by mengqian277** [comment]
谢谢博主！！！  我没指定rowKey，因为我看table的参数说明上说rowKey可以为空就没指定，指定上就没问题了，非常感谢！！！！

**Comment by mmmml-zhao** [comment]
rowKey的默认值 为 id 字段，就dataList得有这个id字段才行~

**Comment by mengqian277** [comment]
哦~，了解了，感谢博主的解答！
