### ISSUE TITLE
大佬，有单独展开的示例么？初学者萌新，表格高度无法跟随纵向数据数量自适应高度，

### ISSUE THREAD

**Issue by sewujishipin** [kawaiiz/table_component#12]
大佬，有单独展开的示例么？初学者萌新，表格高度无法跟随纵向数据数量自适应高度，而且，我的代码真机调试的时候展开折叠延迟很大，没有演示的小程序展开0延迟

**Comment by mmmml-zhao** [comment]
1. 当前仓库即示例小程序的源代码，fork一份，本地运行即可。
2. 表格有tableHeight字段，设定了table 高度，里面使用scroll-view进行滚动的，所以这个自适应高度，你需要自己去改一下，比如把tableHeight的默认值改为auto。
3. 延迟这个，建议fork一份下来，把你的代码贴到小程序里，运行。对比 https://github.com/mmmml-zhao/table_component/blob/master/miniprogram/pages/index/components/expand/ 这个文件夹下面的代码去看。

说个无关的，如果data数据里没有id 字段，请务必设置 rowKey（请注意，rowKey字段指出数据唯一的标识，默认值为id字段，若数据中不存在id字段，则请指定rowKey为数据中的唯一标识字段。）
