### ISSUE TITLE
自定义操作行如果存在多个按钮，如何标识点击的是哪个按钮？

### ISSUE THREAD

**Issue by yuanhuanwebfront** [kawaiiz/table_component#5]
![image](https://user-images.githubusercontent.com/20898808/108939537-d2db0480-768c-11eb-997a-840004aa20d7.png)

**Comment by mmmml-zhao** [comment]
1. 所有的自定义td都是使用同一个action_td组件，在action_td组件内通过当前这一列的columns.key来判断这个td应该显示什么内容。如果仅仅只是监听点击的是哪个td，参考：[https://github.com/kawaiiz/table_component/tree/master/miniprogram/pages/index/components/custom_action/components](url)
2. 如果是单个td内有多个按钮
这个自定义组件是你写的，你给禁用/启用按钮一个catchtap,然后自己写一个函数触发`clickaction`事件，那个value对象（key必须是value）,弄个标识字段判断一下就好，在逻辑页面监听table组件的clickaction事件会获取到你自己定义的value,通过标识字段判断一下就好。
![image](https://user-images.githubusercontent.com/25151442/108944255-5993df80-7695-11eb-8dea-27836d815539.png)
![image](https://user-images.githubusercontent.com/25151442/108944334-7d572580-7695-11eb-8940-7b28f49b14b5.png)
