### ISSUE TITLE
表格单元的高度没有参数可以设置吗？

### ISSUE THREAD

**Issue by LuckyBoy314** [kawaiiz/table_component#8]
没有找到可以直接设置单元格高度的参数

**Comment by mmmml-zhao** [comment]
> 没有找到可以直接设置单元格高度的参数

之所以不写成npm那种包就是因为，大家的需求不一样，对表格的样式要求也不一样。把代码拷贝到自己的项目，根据自己的项目定制化自己的样式，会更好。
